-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/qqconnect_users (
  qqc_user INT UNSIGNED NOT NULL,
  qqc_unionid VARBINARY(64) NOT NULL,
  qqc_appid VARBINARY(255) NOT NULL,
  qqc_nickname VARBINARY(255) DEFAULT NULL,
  qqc_avatar VARBINARY(512) DEFAULT NULL,
  qqc_bound_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY (qqc_user),
  UNIQUE KEY qqc_unionid_unique (qqc_unionid)
)/*$wgDBTableOptions*/;
